live_config_reload: true

window:
  decorations: full

  dimensions:
    columns: 80
    lines: 24

  padding:
    x: 0
    y: 0

scrolling:
  history: 10000

  multiplier: 3

font:
  normal:
    family: Cascadia Code PL
    style: Regular
  size: 14.0
  offset:
    x: 0
    y: 0
  glyph_offset:
    x: 0
    y: 0
  use_thin_strokes: true

draw_bold_text_with_bright_colors: false

colors:
  primary:
    background: '0xfdf6e3'
    foreground: '0x586e75'

  cursor:
    text: '0x93a1a1'
    cursor: '0x586e75'

  normal:
    black: '0x073642'
    red: '0xdc322f'
    green: '0x859900'
    yellow: '0xb58900'
    blue: '0x268bd2'
    magenta: '0xd33682'
    cyan: '0x2aa198'
    white: '0xeee8d5'

  bright:
    black: '0x002b36'
    red: '0xcb4b16'
    green: '0x586e75'
    yellow: '0x657b83'
    blue: '0x839496'
    magenta: '0x6c71c4'
    cyan: '0x93a1a1'
    white: '0xfdf6e3'

bell:
  animation: EaseOutExpo
  duration: 100
  color: '0xeee8d5'

selection:
  semantic_escape_chars: ",│`|:\"' ()[]{}<>"
  save_to_clipboard: false

mouse:
  double_click:
    threshold: 300
  triple_click:
    threshold: 300
  url:
    launcher: open
