live_config_reload: true

env:
  TERM: xterm-truecolor-italic

window:
  dimensions:
    columns: 80
    lines: 24
  padding:
    x: 4
    y: 1

font:
  size: 13.0
  normal:
    family: JetBrains Mono NL
    style: Light
  bold:
    style: Bold
  bold_italic:
    style: Bold Italic
  italic:
    style: Italic

colors:
  primary:
    background: '0xfbf1c7'
    foreground: '0x3c3836'

  normal:
    black:   '0xfbf1c7'
    red:     '0xcc241d'
    green:   '0x98971a'
    yellow:  '0xd79921'
    blue:    '0x458588'
    magenta: '0xb16286'
    cyan:    '0x689d6a'
    white:   '0x7c6f64'

  bright:
    black:   '0x928374'
    red:     '0x9d0006'
    green:   '0x79740e'
    yellow:  '0xb57614'
    blue:    '0x076678'
    magenta: '0x8f3f71'
    cyan:    '0x427b58'
    white:   '0x3c3836'

bell:
  animation: Ease
  duration: 100
  color: '0xfbf1c7'
