#!/bin/bash

set -e

git submodule update --remote --merge -- vim/pack/nwjsmith/start

if ! git diff --shortstat --exit-code -- vim/pack/nwjsmith/start; then
  git add vim/pack/nwjsmith/start
  git commit -m "Update Vim pack"
fi

git submodule update --remote --merge -- emacs.d

emacs \
  --batch \
  --load ~/.emacs.d/init.el \
  --eval="(configuration-layer/update-packages t)"

emacs --batch --load ~/.emacs.d/init.el

if ! git diff --shortstat --exit-code -- emacs.d spacemacs; then
  git add emacs.d spacemacs
  git commit -m "Update Spacemacs"
fi

brew update
brew upgrade
brew bundle --global
brew cask upgrade
brew cleanup

softwareupdate --background --download
