vim.g.do_filetype_lua = 1
vim.g.mapleader = ' '
vim.g.maplocalleader = ','
vim.o.background = 'light'
vim.o.backup = false
vim.o.clipboard = 'unnamedplus'
vim.o.mouse = 'a'
vim.o.swapfile = false
vim.o.termguicolors = true
vim.o.title = true
vim.o.titlestring = "%<%F - nvim"
vim.o.writebackup = false
