add_newline = false

[aws]
disabled = true

[docker_context]
disabled = true

[git_state]
disabled = true

[git_status]
disabled = true

[java]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true
